name: Update server JARs
on:
  push:
    paths:
      - "**.js"
  workflow_dispatch:

jobs:
  update-jar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft-versions: [ 1.13.2, 1.14.4, 1.15.2, 1.16.5, 1.17.1, 1.18.2, 1.19.4, 1.20.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      
      - name: Update ${{ matrix.minecraft-versions }} server JAR
        run: node ./update.js ${{ matrix.minecraft-versions }}
      
      - name: Commit update
        run: |
          git add spigot-${{ matrix.minecraft-versions }}.jar
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update spigot-${{ matrix.minecraft-versions }}.jar"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}